server:
  port: 8765

management:
  endpoints:
    web:
      exposure:
        include: info

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/user-service/**
        - id: swipe-service
          uri: http://swipe-service
          predicates:
            - Path=/swipe-service/**
        - id: attendance-service
          uri: http://attendance-service
          predicates:
            - Path=/attendance-service/**